### ISSUE TITLE
Sign assembly with strong name

### ISSUE THREAD

**Issue by bastianeicher** [ImpromptuNinjas/ZStd#1]
I would like to use your library in my project (a cross-platform package manager, called [Zero Install](https://0install.net/)). However, it targets .NET Framework 4.5 and uses strong-name signed assemblies.

Could you add strong name signing to your assemblies? The [official guidance from Microsoft on topic](https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md) says strong-names are not usually needed anymore but recommends signing any public libraries for compatibility.

I could provide a small PR for this if you're interested.

**Comment by TYoung86** [comment]
Sure. If you could have it produce a separate assembly for creating a separate NuGet package, that would be preferable.

**Comment by Tyler-IN** [comment]
Sure, if you could have it produce a separate assembly to produce a separate NuGet package, that would be preferable.

**Comment by bastianeicher** [comment]
Producing a separate NuGet package is possible of course, but what's the advantage? Anybody currently consuming the non-signed assembly should also be able to consume a signed version without noticing any differences.

**Comment by Tyler-IN** [comment]
Guess we'll see.

**Comment by bastianeicher** [comment]
Thanks, seems to be working fine for me now. :)
