### ISSUE TITLE
Artificial dependency on InfoOf.Fody blocks use in Unity

### ISSUE THREAD

**Issue by ConAim** [ImpromptuNinjas/ZStd#4]
Would be extreamly useful if able to bring to Unity for ECS Burst. But too many dependencies (expecially Fody) had caused so many issues..

**Comment by TYoung86** [comment]
As far as I know, there's nothing stopping this from being used in Unity.

**Comment by Tyler-IN** [comment]
As far as I know, there's nothing preventing this from *actually* being used in Unity.

Can you describe your experience, situation and/or problems?

I'll try to remove the InfoOf.Fody dependency, it's artificial.

**Comment by Tyler-IN** [comment]
v1.4.5.5 should have the dependency removed.
<details><summary>From NuGet.org...</summary>

![image](https://user-images.githubusercontent.com/33945568/88995401-82e3bd00-d2b8-11ea-9750-fc0ef915c9d6.png)

</details>

**Comment by Tyler-IN** [comment]
@ConAim gonna close due to stale tomorrow.
